name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1.1.5
        with:
          pnpm-args: --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pnpm test

  # The Windows runner can be super flaky both with Yarn installs and
  # when launching browser tests, so we allow for retries in those steps.
  test-windows:
    name: Test Windows
    runs-on: windows-2022
    steps:
      - uses: wyvox/action@v1.1.5
        with:
          pnpm-args: --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Test @glint/core
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          timeout_minutes: 20
          command: pnpm --filter '*' @glint/core test
      - name: Test glint-vscode
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          timeout_minutes: 10
          command: pnpm --filter '*' glint-vscode test
      - name: Test @glint/scripts
        run: pnpm --filter '*' @glint/scripts test

  test-floating-deps:
    name: Test Floating Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1.1.5
        with:
          pnpm-args: --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pnpm test

  test-ts-nightly:
    name: Test TypeScript Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1.1.5
        with:
          pnpm-args: --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pnpm test
